# Example usage: kubectl create -f <this_file>

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: web-go
  name: web-go
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-go
  template:
    metadata:
      labels:
        app: web-go
    spec:
      containers:
      - name: web-go
        image: docker.io/echochio/go-web
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: web-go
  name: web-go
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30707
  selector:
    app: web-go
